services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=accounts_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myusapplicationer'
    ports:
      - '5432:5432'
