services:
  postgres:
    image: 'postgres:16'
    container_name: 'postgres'
    command: "postgres -c wal_level=logical"
    environment:
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=expenses_db
      - PGPASSWORD=secret
    ports:
      - '5432:5432'
    healthcheck:
      test: "pg_isready -U application -d expenses_db"
      interval: 2s
      timeout: 20s
      retries: 10
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
